# Numpy!

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import sys

In [2]:
# Display graphs inline in a notebook
%matplotlib inline

## Numpy Array

The array is the fundamental data structure of the Numpy package. Note, this is not the same array as the Python Standard Library `array.array`.

In [5]:
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
c = np.array([[[1, 2, 3], [4,5,6], [7,8,9]]])

In [17]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### Numpy Array Attributes

In [18]:
print('Dimension of a:', a.ndim)
print('Dimension of b:', b.ndim)
print('Dimension of c:', c.ndim)

Dimension of a: 1
Dimension of b: 2
Dimension of c: 3


In [20]:
a.dtype

dtype('int64')

In [21]:
c.size

9

In [22]:
c.itemsize

8

In [24]:
type(b)

numpy.ndarray

### Numpy Operations

In [26]:
b = b.reshape(3,2)

In [27]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
print(b[0,1])

2


In [33]:
print(b[0:,0:])

[[1 2]
 [3 4]
 [5 6]]


In [38]:
x = np.linspace(1, 10, num = 10)

In [39]:
x

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [40]:
x[1:7:2]

array([ 2.,  4.,  6.])

## Comparison with Python Objects and Operations

There are a few different reasons for using Numpy over standard Python objects for work with matrices. The first is space efficiency.

In [47]:
python_obj = range(1000)
numpy_obj = np.arange(1000)
python_list_1 = range(1000000)
python_list_2 = range(1000000)
numpy_array_1 = np.arange(1000000)
numpy_array_2 = np.arange(1000000)

In [45]:
print(sys.getsizeof(python_obj)*len(python_obj))

48000


In [46]:
print(numpy_obj.size*numpy_obj.itemsize)

8000


In [48]:
%%timeit
result_python = [(x,y) for x,y in zip(python_list_1,python_list_2)] 

10 loops, best of 3: 191 ms per loop


In [50]:
%%timeit
result_numpy = numpy_array_1 + numpy_array_2

100 loops, best of 3: 2.05 ms per loop
