# NumPy!

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys

In [2]:
# Display graphs inline in a notebook
%matplotlib inline

## NumPy Array

The array is the fundamental data structure of the Numpy package. Note, this is not the same array as the Python Standard Library `array.array`. The type of the array is `numpy.ndarray` where `nd` refers to *N-Dimensional*.

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c = np.array([[[1, 2, 3], [4,5,6], [7,8,9]]])

In [8]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### NumPy Array Creation

NumPy arrays can be created a number of different ways. One of the simplest ways is to pass a Python list into the `numpy.array()` method.

In [28]:
list_to_array = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
array_from_list = np.array(list_to_array)
array_from_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

When creating an array we can also specify the `dtype`, or data type of the elements within the array.

In [30]:
dtype_array = np.array(list_to_array, dtype='int32')
dtype_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int32)

We can also randomly generate an array using the `numpy.random.rand` method, passing the dimensions of the array.

In [38]:
random_array = np.random.rand(3,2)
random_array

array([[ 0.10710629,  0.08201775],
       [ 0.88871207,  0.59748995],
       [ 0.10628125,  0.74882672]])

We can also generate arrays that have certain values, namely zeros and ones.

In [45]:
ones_array = np.ones(3)
print(ones_array)
zeros_array = np.zeros((5,4))
print(zeros_array)

[ 1.  1.  1.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


### NumPy Array Attributes

In [9]:
print('Dimension of a:', a.ndim)
print('Dimension of b:', b.ndim)
print('Dimension of c:', c.ndim)

Dimension of a: 1
Dimension of b: 2
Dimension of c: 3


In [10]:
a.dtype

dtype('int64')

In [11]:
c.size

9

In [32]:
c.itemsize
c.dtype.itemsize

8

In [13]:
type(b)

numpy.ndarray

### Numpy Operations

In [14]:
b = b.reshape(3,2)

In [15]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
print(b[0,1])

2


In [17]:
print(b[0:,0:])

[[1 2]
 [3 4]
 [5 6]]


In [18]:
x = np.linspace(1, 10, num = 10)

In [19]:
x

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [20]:
x[1:7:2]

array([ 2.,  4.,  6.])

## Comparison with Python Objects and Operations

There are a few different reasons for using Numpy over standard Python objects for work with matrices. The first is space efficiency.

In [21]:
python_obj = range(1000)
numpy_obj = np.arange(1000)
python_list_1 = range(1000000)
python_list_2 = range(1000000)
numpy_array_1 = np.arange(1000000)
numpy_array_2 = np.arange(1000000)

In [22]:
print(sys.getsizeof(python_obj)*len(python_obj))

48000


In [23]:
print(numpy_obj.size*numpy_obj.itemsize)

8000


In [26]:
%%timeit
result_python = [x + y for x,y in zip(python_list_1,python_list_2)] 

10 loops, best of 3: 115 ms per loop


In [25]:
%%timeit
result_numpy = numpy_array_1 + numpy_array_2

1000 loops, best of 3: 1.87 ms per loop
